# Generated by Django 4.2.4 on 2024-03-26 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_publisherinfo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisherinfo',
            name='image',
            field=models.ImageField(default='', upload_to='user/media/uploads'),
        ),
    ]
